#ifndef CLIENT_PROTOCOL_H_INCLUDED
#define CLIENT_PROTOCOL_H_INCLUDED

enum { // client to server protocol
    RAW_TEXT=0,
    MOVE_TO=1,
    SEND_PM=2,
    GET_PLAYER_INFO=5,
    SIT_DOWN=7,
    SEND_ME_MY_ACTORS=8,
    SEND_OPENING_SCREEN=9,
    SEND_VERSION=10,
    HEARTBEAT=14,
    USE_OBJECT=16,
    LOOK_AT_INVENTORY_ITEM=19,
    MOVE_INVENTORY_ITEM=20,
    HARVEST=21,
    DROP_ITEM=22,
    PICK_UP_ITEM=23,
    INSPECT_BAG=25,
    LOOK_AT_MAP_OBJECT=27,
    SEND_PARTIAL_STATS=49,
    PING_RESPONSE=60,
    SET_ACTIVE_CHANNEL=61,
    LOG_IN=140,
    CREATE_CHAR=141,
    GET_DATE=230,
    GET_TIME=231,
    SERVER_STATS=232
};

#endif // CLIENT_PROTOCOL_H_INCLUDED
