#ifndef SERVER_PROTOCOL_H_INCLUDED
#define SERVER_PROTOCOL_H_INCLUDED

enum { // server to client protocol
    RAW_TEXT=0,
    ADD_ACTOR=2,
    YOU_ARE=3,
    SYNC_CLOCK=4,
    NEW_MINUTE=5,
    REMOVE_ACTOR=6,
    CHANGE_MAP=7,
    HERE_YOUR_STATS=18,
    HERE_YOUR_INVENTORY=19,
    GET_NEW_INVENTORY_ITEM=21,
    HERE_YOUR_GROUND_ITEMS=23,
    GET_NEW_GROUND_ITEM=24,
    S_CLOSE_BAG=26,
    GET_NEW_BAG=27,
    DESTROY_BAG=29,
    ADD_NEW_ENHANCED_ACTOR=51,
    GET_ACTIVE_CHANNELS=71,
    YOU_DONT_EXIST=249,
    LOG_IN_OK=250,
    LOG_IN_NOT_OK=251,
    CREATE_CHAR_OK=252,
    CREATE_CHAR_NOT_OK=253
};

#endif // SERVER_PROTOCOL_H_INCLUDED
